name: Continuous Deployment

on: [push]

jobs:
  bump-homebrew-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Bump Homebrew formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          formula: git-delta
          token: ${{ secrets.GITHUB_TOKEN }}
